import type { OutputRecord } from './types.js';

export function buildReport(record: OutputRecord): string {
  const { transcription, summary, audioName, processedAt } = record;
  const now = processedAt.toLocaleString('ar-EG', { timeZone: 'Africa/Cairo' });

  const lines: string[] = [
    '# Audio Intelligence Report',
    '',
    `**Generated:** ${now}`,
    `**Audio:** ${audioName}`,
    `**ID:** ${record.id}`,
    '',
    '---',
    '',
    '## Transcription',
    '',
    `| Field | Value |`,
    `|-------|-------|`,
    `| Provider | ${transcription.provider} |`,
    `| Model | ${transcription.model ?? '—'} |`,
    `| Language | ${transcription.language ?? 'unknown'} |`,
    `| Duration | ${transcription.durationSec != null ? transcription.durationSec.toFixed(1) + 's' : '—'} |`,
    `| Characters | ${transcription.text.length.toLocaleString()} |`,
    `| Segments | ${transcription.segments?.length ?? 0} |`,
    `| Words (timestamped) | ${transcription.words?.length ?? 0} |`,
    '',
    '### Full Transcript',
    '',
    transcription.text || '*(empty)*',
    '',
  ];

  if (transcription.segments?.length) {
    lines.push('### Segments (first 20)', '');
    lines.push('| # | Start | End | Speaker | Text |');
    lines.push('|---|-------|-----|---------|------|');
    transcription.segments.slice(0, 20).forEach((seg, i) => {
      const speaker = seg.speaker != null ? String(seg.speaker) : '—';
      const text    = seg.text.replace(/\|/g, '\\|').slice(0, 80);
      lines.push(`| ${i + 1} | ${seg.start.toFixed(2)}s | ${seg.end.toFixed(2)}s | ${speaker} | ${text} |`);
    });
    if (transcription.segments.length > 20) {
      lines.push(`\n*... و ${transcription.segments.length - 20} segment أخرى في segments.json*`);
    }
    lines.push('');
  }

  lines.push('---', '');

  if (summary) {
    lines.push(
      '## Summary',
      '',
      `| Field | Value |`,
      `|-------|-------|`,
      `| Provider | ${summary.provider} |`,
      `| Model | ${summary.model ?? '—'} |`,
      `| Input tokens | ${summary.usage?.inputTokens?.toLocaleString() ?? '—'} |`,
      `| Output tokens | ${summary.usage?.outputTokens?.toLocaleString() ?? '—'} |`,
      '',
      '### Content',
      '',
      summary.summary,
      '',
    );
    if (summary.actionItems?.length) {
      lines.push('### Action Items', '');
      summary.actionItems.forEach((item, i) => lines.push(`${i + 1}. ${item}`));
      lines.push('');
    }
    if (summary.topics?.length) {
      lines.push('### Topics', '');
      summary.topics.forEach((t) => lines.push(`- ${t}`));
      lines.push('');
    }
  } else {
    lines.push('## Summary', '', '*(not requested or skipped)*', '');
  }

  lines.push('---', '', '*Generated by audio-intelligence*');
  return lines.join('\n');
}
